title: Xing Chen
position: Assistant Professor
affiliation: School of International Relations and Public Affairs, Fudan University
email: xingc (at) fudan.edu.cn
keywords: Xing Chen
description: XingChen's academic personal homepage

