title: Xing Chen(陈醒)
position: Assistant Professor
affiliation: Fudan University,School of International Relations and Public Affairs,
email: xingc (at) fudan.edu.cn
keywords: Xing Chen
google_scholar: https://scholar.google.com/citations?hl=zh-CN&user=LvEEvEgAAAAJ
github_link: https://github.com/xingchen0123
linkedin: https://www.linkedin.com/
avatar: ./assets/img/photo.jpg
google_analytics: UA-111540567-4
favicon: ./assets/img/2.2_meitu_cut.jpg
description: XingChen's academic personal homepage
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light
