title: Xing CHEN
position: Assistant Professor
affiliation: Fudan University
email: xingc@fudan.edu.cn
keywords: Xing Chen

# If you don't need one of them, you may delete the corresponding line.
google_scholar: https://scholar.google.com/citations?hl=zh-CN&user=LvEEvEgAAAAJ
cv_link: assets/CV.pdf


# Images (e.g., your profile picture and your website's favicon) 
# "favicon" and "favicon_dark" are used for the light and dark modes, respectively. 
avatar: ./assets/img/photo3.jpg
favicon: ./assets/img/2.2_meitu_cut.jpg
favicon_dark: ./assets/img/2.2_meitu_cut.jpg

