title: Xing Chen(陈醒)
position: Assistant Professor
affiliation: Fudan University
email: xingc (at) fudan.edu.cn
keywords: Xing Chen

# If you don't need one of them, you may delete the corresponding line.
google_scholar: https://scholar.google.com/citations?hl=zh-CN&user=LvEEvEgAAAAJ
cv_link: assets/files/curriculum_vitae.pdf
github_link: https://github.com/
linkedin: https://www.linkedin.com/
twitter: https://twitter.com/

# Images (e.g., your profile picture and your website's favicon) 
# "favicon" and "favicon_dark" are used for the light and dark modes, respectively. 
avatar: ./assets/img/avatar.png
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

